apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: {{ .Values.cronSchedule }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: gpg
            secret:
              secretName: {{ template "logscrapper.fullname" . }}-gpg
          containers:
            - name: {{ .Release.Name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
              - name: LOGCLI_PATH
                value: {{ .Values.logcliPath }}
              - name: LOG_ENDPOINT
                value: {{ .Values.logEndpoint }}
              - name: START_TIME
                value: {{ .Values.startTime }}
              - name: END_TIME
                value: {{ .Values.endTime }}
              - name: OUTPUT_FILE
                value: {{ .Values.outputFile }}
              - name: COMPRESSED_FILE
                value: {{ .Values.compressedFile }}
              - name: ENCRYPTED_FILE
                value: {{ .Values.encryptedFile }}
              - name: S3_BUCKET
                value: {{ .Values.s3Bucket }}
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ template "logscrapper.fullname" . }}
                    key: awsAccessKeyId
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ template "logscrapper.fullname" . }}
                    key: awsSecretAccessKey
              - name: AWS_DEFAULT_REGION
                value: {{ .Values.awsDefaultRegion }}
              command: ["/bin/bash"]
              args: ["logscapper.sh", "{{ .Values.logcliQuery }}"]
              volumeMounts:
              - name: gpg
                readOnly: true
                mountPath: "/etc/gpg"
          restartPolicy: OnFailure
