{{- $ := . }}
{{- range $k, $v := .Values.instances }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "logscrapper.fullname" $ }}-{{ $k }}
spec:
  schedule: {{ $v.cronSchedule }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: gpg
            secret:
              secretName: {{ template "logscrapper.fullname" $ }}-gpg
          containers:
          - name: logscrapper
            image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            env:
            - name: LOG_ENDPOINT
              value: {{ $.Values.logEndpoint }}
            - name: START_TIME
              value: {{ $v.startTime }}
            - name: END_TIME
              value: {{ $v.endTime }}
            - name: S3_PATH
              value: {{ $.Values.s3Path }}
            - name: GPG_PUBLIC_KEY_FILE
              value: "/etc/gpg/gpg_public_key.asc"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "logscrapper.fullname" $ }}
                  key: awsAccessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "logscrapper.fullname" $ }}
                  key: awsSecretAccessKey
            - name: AWS_DEFAULT_REGION
              value: {{ $.Values.awsDefaultRegion }}
            args: ['{{ $v.logcliQuery }}']
            volumeMounts:
            - name: gpg
              readOnly: true
              mountPath: "/etc/gpg"
          restartPolicy: OnFailure
{{- end }}
