apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.awsSecretName }}
type: Opaque
data:
  awsAccessKeyId: {{ .Values.env.awsAccessKeyId | b64enc }}
  awsSecretAccessKey: {{ .Values.env.awsSecretAccessKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gpgSecretName }}
type: Opaque
data:
  gpgPublicKey: {{ .Values.env.gpgPublicKey | b64enc }}
