apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logscrapper.fullname" . }}
type: Opaque
data:
  awsAccessKeyId: {{ .Values.env.awsAccessKeyId | b64enc }}
  awsSecretAccessKey: {{ .Values.env.awsSecretAccessKey | b64enc }}
