apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logscrapper.fullname" . }}-gpg
  labels:
    {{- include "logscrapper.labels" . | nindent 4 }}
type: Opaque
data:
  gpg_public_key.asc: {{ .Values.gpgPublicKey | b64enc | quote }}
