apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logscrapper.fullname" . }}
type: Opaque
data:
  awsAccessKeyId: {{ .Values.awsAccessKeyId | b64enc | quote }}
  awsSecretAccessKey: {{ .Values.awsSecretAccessKey | b64enc | quote }}
