awsSecretAccessKey: ENC[AES256_GCM,data:QZbCIOY+aXocGLe6DXAYsB8MEexts4gLwUmf++Y4S0vnliXaw2sXNA==,iv:+BHkgZQjA7AdKJ+9ZLSQm0oXZkcCgRWoueC33lkdId4=,tag:gNwvCZR7BuClt65uLR4BDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-02T07:58:20Z"
    mac: ENC[AES256_GCM,data:HT6Y+DmkvS5PwH26zycEAh51ElXh14RH5KBV8Lgwn6TY4K4sZVy2qtji06pQznOLP8bsNTqqfa4IlnhHW/ijqGrbD8PToVPvf1A4b7OcUEXu5iQ7mLU8Dxd18lIzVkodu2Hwj9fuypMFrPTg/OOPzAwE8wESYqWMw2RSkUCREpI=,iv:WOOYccjZX7a6HCBVym5PQNfM28X0W0qvRC9HQcHZApI=,tag:PQcLWycLYYeORmPmZIxTlw==,type:str]
    pgp:
        - created_at: "2023-06-02T07:58:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAywVydcrIlYUAQ/+KFL2MK4agLgErm/xJ6ItK2kNzJJ1V/uWckfSOvuTNg/g
            Of327tF9hBuYKLj0sarq1zFiQphFHCgxFaK71eiDLWDO2Dd7PcjwsqRr3HrvzJw4
            c+fQN7QPLYQgnSm3GdVsS6faOpg/n53MDYITvdlJkOA7m7TAglMj8dQQSm9JXee3
            WSLyW9xcOsBbQixzuQ0c8ucQZvU0/hgnwKZDxSqpgjeB+GFS9oxDg3P+O4gbAACp
            j1OZ6dX3M3CGBvvuDxbmoXIiysVPpP+d4IYB84bgOrC+dhA5dkVXWmGTHL27XKKs
            kt4L8Eu5kIMFS+LCjYORHoekX10/x0uI2ASE2V3jkspLjs+T74ZQKjzjGbBqULrf
            wU6Ghl7GwO07zKGsnpjtRlt9AGqzKLKvU0RJBsO1dPolxYXmklihMEcZAmDqtgZ7
            9VvdvUin76UdjWbsgv0Ww0IXCS4ly5YQ4gAdGkgyBiMOkvkl2wSw3MCuwXHOyfPX
            va89Jv+ffRwJuC6BqyMKivby2khO2V4pZhJailIMnUeJHmGZjmSidTPK1Ji19EAs
            2d2WnOsn+edPJS80Hjp7nFXMwGUQO3X9ffMxKTQz1z7yxvjE0xW/XNk+OygDRLm3
            uI81+wS947ErNDtcqru+jYbnGoT1rTSP63qWZ72lwmvd32RLaYzwAy3+l1/SOgHS
            XgH/F7lhSGW6d2EPu06iuwUGq9LK1IEpLT2eGwHLsXmeeM1w+EKLK9mzmY6G6jx1
            FmGkj7Vh7noinH2oWaUU9n8Sp6CgvgKjlKRUPNpgrl0OPv/Rdm23UxuVYAUKG44=
            =0z/i
            -----END PGP MESSAGE-----
          fp: 893BD14E345457BFA63814AEEF06E261D71DC400
    unencrypted_suffix: _unencrypted
    version: 3.7.1
